from datetime import date, datetime
from typing import Any

from app.database.postgres.loaders import _air_quality_time, _upsert, _utc


def save_environmental_data(
    connection: Any,
    region: dict[str, Any],
    weather: dict[str, Any],
    hotspots: dict[str, Any],
    air_quality: dict[str, Any],
    forecast: dict[str, Any],
) -> dict[str, int]:
    """Upsert only the four environmental tables in environment_conditions."""
    region_id = region["id"]
    weather_count = _upsert(connection, """INSERT INTO public.tb_r_weather (regency_city_id,weather,measured_at,temperature,humidity,precipitation_mm,wind_speed_kmh,wind_direction,source_name) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s) ON CONFLICT (regency_city_id,measured_at,source_name) DO UPDATE SET weather=EXCLUDED.weather,temperature=EXCLUDED.temperature,humidity=EXCLUDED.humidity,precipitation_mm=EXCLUDED.precipitation_mm,wind_speed_kmh=EXCLUDED.wind_speed_kmh,wind_direction=EXCLUDED.wind_direction""", ((region_id,item["weather"],datetime.combine(date.fromisoformat(item["time"]),datetime.min.time()),item["temperature_c"],item["humidity_pct"],item["precipitation_mm"],item["wind_speed_kmh"],item["wind_direction"],weather["source"]) for item in weather["data"]))
    hotspot_count = _upsert(connection, """INSERT INTO public.tb_r_hotspot (regency_city_id,latitude,longitude,detected_at,confidence,frp_mw,daynight,sensor,brightness_k,source_name) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) ON CONFLICT (regency_city_id,detected_at,latitude,longitude,source_name) DO UPDATE SET confidence=EXCLUDED.confidence,frp_mw=EXCLUDED.frp_mw,daynight=EXCLUDED.daynight,sensor=EXCLUDED.sensor,brightness_k=EXCLUDED.brightness_k""", ((region_id,item["latitude"],item["longitude"],_utc(item["time"]),item["confidence"],item["frp_mw"],item["daynight"],hotspots["sensor"],item["brightness_k"],hotspots["source"]) for item in hotspots["data"]))
    air_quality_count = _upsert(connection, """INSERT INTO public.tb_r_air_quality (regency_city_id,measured_at,pm25,pm10,co,no2,aqi,dust_ugm3,aerosol_optical_depth,uv_index,source_name) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) ON CONFLICT (regency_city_id,measured_at,source_name) DO UPDATE SET pm25=EXCLUDED.pm25,pm10=EXCLUDED.pm10,co=EXCLUDED.co,no2=EXCLUDED.no2,aqi=EXCLUDED.aqi,dust_ugm3=EXCLUDED.dust_ugm3,aerosol_optical_depth=EXCLUDED.aerosol_optical_depth,uv_index=EXCLUDED.uv_index""", ((region_id,_air_quality_time(item["time"],air_quality["period"]["timezone"]),item["pm2_5_ugm3"],item["pm10_ugm3"],item["carbon_monoxide_ugm3"],item["nitrogen_dioxide_ugm3"],item["us_aqi"],item["dust_ugm3"],item["aerosol_optical_depth"],item["uv_index"],air_quality["source"]) for item in air_quality["data"]))
    forecast_count = _upsert(connection, """INSERT INTO public.tb_r_weather_forecast (regency_city_id,forecast_date,issued_at,weather,weather_code,temperature_min_c,temperature_max_c,temperature_avg_c,humidity_avg_pct,precipitation_mm,precipitation_probability_max_pct,wind_speed_max_kmh,wind_direction_deg,wind_direction,uv_index_max,source_name) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) ON CONFLICT (regency_city_id,forecast_date,source_name) DO UPDATE SET issued_at=EXCLUDED.issued_at,weather=EXCLUDED.weather,weather_code=EXCLUDED.weather_code,temperature_min_c=EXCLUDED.temperature_min_c,temperature_max_c=EXCLUDED.temperature_max_c,temperature_avg_c=EXCLUDED.temperature_avg_c,humidity_avg_pct=EXCLUDED.humidity_avg_pct,precipitation_mm=EXCLUDED.precipitation_mm,precipitation_probability_max_pct=EXCLUDED.precipitation_probability_max_pct,wind_speed_max_kmh=EXCLUDED.wind_speed_max_kmh,wind_direction_deg=EXCLUDED.wind_direction_deg,wind_direction=EXCLUDED.wind_direction,uv_index_max=EXCLUDED.uv_index_max""", ((region_id,item["forecast_date"],forecast["issued_at"],item["weather"],item["weather_code"],item["temperature_min_c"],item["temperature_max_c"],item["temperature_avg_c"],item["humidity_avg_pct"],item["precipitation_mm"],item["precipitation_probability_max_pct"],item["wind_speed_max_kmh"],item["wind_direction_deg"],item["wind_direction"],item["uv_index_max"],forecast["source"]) for item in forecast["data"]))
    return {"weather": weather_count, "hotspots": hotspot_count, "air_quality": air_quality_count, "forecast": forecast_count}
